### ISSUE TITLE
Unable to resolve action `autero1/action-gotestsum@v2`

### ISSUE THREAD

**Issue by epot** [autero1/action-gotestsum#45]
I am trying to follow the documentation but I get:

```
Error: Unable to resolve action `autero1/action-gotestsum@v2`, unable to find version `v2`
```

Is there an issue with the latest version?

**Comment by sveitser** [comment]
It works for me with v2.0.0

```
      - name: Install latest gotestsum
        uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: 1.12.0
```
