### ISSUE TITLE
Deprecation warning related to the use of Node.js 16

### ISSUE THREAD

**Issue by dekimsey** [autero1/action-gotestsum#46]
Using the action generates warning annotations in GHA like the following:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: autero1/action-gotestsum@7263b9d73912eec65f46337689e59fac865c425f
```

Apologies, unfortunately I'm not a Node/Typescript person, so I'm not particularly comfortable trying to submit a change. :(

**Comment by gertd** [comment]
For those who cannot or do not want to wait on the PR https://github.com/autero1/action-gotestsum/pull/47 to be merged, there is a fork available on https://github.com/gertd/action-gotestsum, which can be used as:

```
      -
        name: Test Setup
        uses: gertd/action-gotestsum@v3.0.0
        with:
          gotestsum_version: ${{ env.GO_TESTSUM_VERSION }}
```
